version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: my_app
    container_name: my_app
    ports:
      - "3001:3001"
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    command: npm run dev
  mongo:
    image: mongo:4
    container_name: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./.docker/mongo/data:/data/db
