module.exports = {
  JWT_EXPIRES_IN: 900, // 15 minutes
  JWT_REFRESH_EXPIRES_IN: 2592000, // 1 month
  SERVER_JWT_SECRET: process.env.SERVER_JWT_SECRET,
  SERVER_JWT_SECRET_REFRESH: process.env.SERVER_JWT_SECRET_REFRESH,
  SERVER_JWT_SECRET_ADMIN: process.env.SERVER_JWT_SECRET_ADMIN,
  SERVER_JWT_SECRET_REFRESH_ADMIN: process.env.SERVER_JWT_SECRET_REFRESH_ADMIN
};
